### ISSUE TITLE
require 'uri' をしないと動かない場合がある

### ISSUE THREAD

**Issue by YU-TAYU** [rakuten-ws/rws-ruby-sdk#18]
# 概要
bundlerを使わない場合、require 'uri'しないと動かない場合があるので直せないでしょうか。

# 前提条件
* bundlerではインストールしていません。
* gem installでインストールしました。

# 詳細
bundlerを使わずにgem install した環境で以下のサンプルを実行させようとすると以下のエラーがでました。

```ruby
require'rakuten_web_service'

RakutenWebService.configuration do |c|
  c.application_id = 'ID'
  c.affiliate_id ='ID'
end

items = RakutenWebService::Ichiba::Item.search(:keyword => 'Ruby') # This returns Enamerable object
```
ターミナルで
```
$ ruby 2test_rakuten.rb
```
と実行すると以下のエラーがでました。
```
/Users/yuki/gem/gems/rakuten_web_service-0.6.2/lib/rakuten_web_service/client.rb:18:in `initialize': uninitialized constant RakutenWebService::Client::URI (NameError)
	from /Users/username/gem/gems/rakuten_web_service-0.6.2/lib/rakuten_web_service/search_result.rb:8:in `new'
	from /Users/username/gem/gems/rakuten_web_service-0.6.2/lib/rakuten_web_service/search_result.rb:8:in `initialize'
	from /Users/username/gem/gems/rakuten_web_service-0.6.2/lib/rakuten_web_service/resource.rb:29:in `new'
	from /Users/username/gem/gems/rakuten_web_service-0.6.2/lib/rakuten_web_service/resource.rb:29:in `search'
	from 2test_rakuten.rb:8:in `<main>'
```
ライブラリのソースを見て調べてみて
```ruby
require 'rakuten_web_service'
require 'uri'
```
と記入するとエラーは解消できました。
ソースを見ないとわからなかったので、解消されると嬉しいです。

**Comment by satoryu** [comment]
@YU-TAYU #12 で類似した現象が報告されているのですが、

* 実行したruby のバージョン
* 実行したrakuten_web_serviceのバージョン

は何でしょうか？

**Comment by YU-TAYU** [comment]
rakuten_web_service (0.6.2)
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14] です。

**Comment by cesare** [comment]
`ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]` (rbenv 利用) でも同様でした。

どうも bundler を使わずに `gem install` した場合に、この問題が起きるように見えます。

**Comment by satoryu** [comment]
@cesare @YU-TAYU 

ありがとうございます！確かに、`bundler` 使うと大丈夫そうですね。。。

```sh
[tatsuya.b.sato:work/rws-ruby-sdk] ruby ./examples/ichiba_item_search.rb
/usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rakuten_web_service-0.6.2/lib/rakuten_web_service/client.rb:18:in `initialize': uninitialized constant RakutenWebService::Client::URI (NameError)
        from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rakuten_web_service-0.6.2/lib/rakuten_web_service/search_result.rb:8:in `new'
        from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rakuten_web_service-0.6.2/lib/rakuten_web_service/search_result.rb:8:in `initialize'
        from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rakuten_web_service-0.6.2/lib/rakuten_web_service/resource.rb:29:in `new'
        from /usr/local/var/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rakuten_web_service-0.6.2/lib/rakuten_web_service/resource.rb:29:in `search'
        from ./examples/ichiba_item_search.rb:12:in `<main>'
[tatsuya.b.sato:work/rws-ruby-sdk] bundle exec ruby ./examples/ichiba_item_search.rb                                                                                                          (git|master)
/Users/tatsuya.b.sato/Projects/work/rws-ruby-sdk/lib/rakuten_web_service/client.rb:31:in `get': client_id or access_token is required (RakutenWebService::WrongParameter)
        from /Users/tatsuya.b.sato/Projects/work/rws-ruby-sdk/lib/rakuten_web_service/search_result.rb:55:in `query'
        from /Users/tatsuya.b.sato/Projects/work/rws-ruby-sdk/lib/rakuten_web_service/search_result.rb:17:in `each'
        from ./examples/ichiba_item_search.rb:14:in `first'
        from ./examples/ichiba_item_search.rb:14:in `<main>'
```

**Comment by satoryu** [comment]
#23 で解決いたしました。

Thank you for all guys @YU-TAYU @cesare :+1:
